### ISSUE TITLE
Incompatible with mustache gem >= 1.0.0

### ISSUE THREAD

**Issue by rwd** [agoragames/stache#47]
stache is not compatible with the mustache gem for versions from 1.0.0.

Attempting to render a view/template that worked with mustache gem 0.99.8, 1.0.0 fails with a NoMethodError and the message:

> undefined method `update' for #<Stache::Mustache::FasterContext:0x000000052eb7b0>

**Comment by alexander-ruehle** [comment]
Same here.

**Comment by alexander-ruehle** [comment]
thank you!

**Comment by rwd** [comment]
Confirmed, this fixes the issue, thanks!
